### ISSUE TITLE
[Bug]: Broker applications in Draft and Released state not appearing for selection from GUI

### ISSUE THREAD

**Issue by dennis-brinley** [SolaceLabs/ep-asyncapi-sap-is-converter#9]
### Bug Description

**Updated description** - I think the root cause is that fields were added to consumer configuration. If an app version has a consumer, then an error is caught parsing the data returned from event portal in the codegen GUI. The versions are not available for download.

**Two examples are shown, one requiring broker update and the other without assigned environment. Both instances have at least one released version. Neither displays any versions available for IS IFlow code generation**

1. Order Validated Service, Broker assigned to Env requires update
![image (1)](https://github.com/user-attachments/assets/03270c4d-6a61-4f4a-b7c1-9c78421a4247)
2. Email Service, No Runtime environments assigned
<img width="1473" alt="image" src="https://github.com/user-attachments/assets/867a1083-4375-4142-8353-a28218fa8cc3">

**In both cases, versions are not displayed to generate code:**
<img width="1584" alt="image" src="https://github.com/user-attachments/assets/986059f0-81f3-4616-8a5c-20854b9b625b">

## Steps taken
- Reverted to an earlier commit (pom version == 1.0.0), same error was observed

## Logs/Stack Trace
```
2024-07-19T13:39:31.457-04:00  INFO 88476 --- [ep-asyncapi-sap-is-converter] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-07-19T13:39:31.473-04:00 ERROR 88476 --- [ep-asyncapi-sap-is-converter] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'apiClientUtil': Lookup method resolution failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.checkLookupMethods(AutowiredAnnotationBeanPostProcessor.java:497) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:367) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1294) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.6.jar!/:6.1.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.6.jar!/:6.1.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.6.jar!/:6.1.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.5.jar!/:3.2.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.5.jar!/:3.2.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.5.jar!/:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.5.jar!/:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.5.jar!/:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.5.jar!/:3.2.5]
	at ep.asyncapi.tool.sap.is.converter.EpAsyncapiSapIsConverterApplication.main(EpAsyncapiSapIsConverterApplication.java:12) ~[classes!/:1.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[ep-asyncapi-sap-is-converter-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[ep-asyncapi-sap-is-converter-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[ep-asyncapi-sap-is-converter-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[ep-asyncapi-sap-is-converter-1.0.0.jar:1.0.0]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [ep.asyncapi.tool.sap.is.converter.commons.ApiClientUtil] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@79fc0f2f]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.1.6.jar!/:6.1.6]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:320) ~[spring-core-6.1.6.jar!/:6.1.6]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.checkLookupMethods(AutowiredAnnotationBeanPostProcessor.java:475) ~[spring-beans-6.1.6.jar!/:6.1.6]
	... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/solace/cloud/ep/designer/ApiClient
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.1.6.jar!/:6.1.6]
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.solace.cloud.ep.designer.ApiClient
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[ep-asyncapi-sap-is-converter-1.0.0.jar:1.0.0]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 33 common frames omitted
```

### Expected Behavior

All application versions in draft and released states should be available for codegen/download

### Steps to Reproduce

run code gen and select any application defined with consumers

**Comment by dennis-brinley** [comment]
It appears that this is the root cause:
The field `extendedAttributes` in the JSON string is not defined in the `Consumer` properties.

Most likely caused by new fields added by product. The lib ep-designer-client should be updated. Not sure where that came from. Also, the lib code should be annotated so that new fields do not cause failures.
